services:
  bestellservice:
    build:
      context: . # Da wir Microservices als Monorepo nutzen, muss die Parent-POM mitgelesen werden
      dockerfile: bestell-service/Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/bestellservice
    depends_on:
      - db
      - kafka

  bestandservice:
    build:
      context: .
      dockerfile: bestand-service/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/bestandservice
    depends_on:
      - db
      - kafka

  benachrichtigungservice:
    build:
      context: .
      dockerfile: benachrichtigung-service/Dockerfile
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/benachrichtigungservice
    depends_on:
      - db
      - kafka

  nachbestellservice:
    build:
      context: .
      dockerfile: nachbestell-service/Dockerfile
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/nachbestellservice
    depends_on:
      - db
      - kafka

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bestellservice
    ports:
      - "5432:5432"
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d

  kafka:
    image: wurstmeister/kafka
    environment:
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    ports:
      - "9092:9092"
    depends_on:
      - db
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper
    environment:
      - ZOOKEEPER_ADVERTISED_LISTENERS=zookeeper:2181
      - ZOOKEEPER_LISTENERS=zookeeper:2181
      - ZOOKEEPER_LISTENER_SECURITY_PROTOCOL=PLAINTEXT
      - ZOOKEEPER_CLIENT_PORT=2181
    ports:
      - "2181:2181"

  akhq:
    image: tchiotludo/akhq
    ports:
      - "8085:8080"  # AKHQ läuft über http://localhost:8085
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            kafka-cluster:
              properties:
                bootstrap.servers: "kafka:9092"
    depends_on:
      - kafka